### ISSUE TITLE
Will you add Mixed-Integer Program bindings

### ISSUE THREAD

**Issue by ctriley** [KardinalAI/cp_sat#28]
I was wondering if you intended to fill out the bindings for the entirety of OR-Tools, or just the CP subset.

Thanks!

**Comment by TeXitoi** [comment]
As is we have the features that we need, so no evolution is planned. We will accept PR to add CP_SAT features that are not yet covered, as listed in the issues.

We don't plan to cove other OR-Tools parts. If someone want to do such a project, this project can be imported into.
